development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

editstore_development:
  adapter: sqlite3
  database: db/editstore_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

editstore_test:
  adapter: sqlite3
  database: db/editstore_test.sqlite3
  pool: 5
  timeout: 5000