development:
  jetty_port: 8983
  java_opts:
      - "-XX:MaxPermSize=128m"
      - "-Xmx256m"

test:
  jetty_port: <%= ENV["TEST_JETTY_PORT"] || '8888' %>
  startup_wait: 200
  java_opts:
      - "-XX:MaxPermSize=128m"
      - "-Xmx256m"